--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: Raj
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    name character varying,
    age integer,
    gender character varying
);


ALTER TABLE public.actors OWNER TO "Raj";

--
-- Name: actors_id_seq; Type: SEQUENCE; Schema: public; Owner: Raj
--

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actors_id_seq OWNER TO "Raj";

--
-- Name: actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: Raj
--

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;


--
-- Name: movies; Type: TABLE; Schema: public; Owner: Raj
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title character varying,
    release_date date
);


ALTER TABLE public.movies OWNER TO "Raj";

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: Raj
--

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movies_id_seq OWNER TO "Raj";

--
-- Name: movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: Raj
--

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;


--
-- Name: actors id; Type: DEFAULT; Schema: public; Owner: Raj
--

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);


--
-- Name: movies id; Type: DEFAULT; Schema: public; Owner: Raj
--

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: Raj
--

COPY public.actors (id, name, age, gender) FROM stdin;
1	Brad	25	male
2	Jen	25	female
3	Brad	30	male
4	Julia	35	female
5	Joe	40	male
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: Raj
--

COPY public.movies (id, title, release_date) FROM stdin;
1	Robots	2020-10-01
2	Cars	2020-10-02
3	Cats	2020-10-03
4	Bats	2020-10-04
\.


--
-- Name: actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Raj
--

SELECT pg_catalog.setval('public.actors_id_seq', 5, true);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Raj
--

SELECT pg_catalog.setval('public.movies_id_seq', 4, true);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: Raj
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: Raj
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

